dist: trusty
sudo: false

language: go
go:
  - 1.9

go_import_path: github.com/zaquestion/lab

script:
  - go test ./...

deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: master
    tags: true

notifications:
  email: false
